test_dict = {'Insect-Flower': ['insect-flower_flower',
  'insect-flower_insect',
  'valence_pleasant',
  'valence_unpleasant'],
 'Gender-Science': ['gender_male',
  'gender_female',
  'gender_science',
  'gender_liberal-arts'],
 'Gender-Career': ['gender_male',
  'gender_female',
  'gender_career',
  'gender_family'],
 'Intersectional-Gender-Science-MF': ['intersectional_male',
  'intersectional_female',
  'gender_science',
  'gender_liberal-arts'],
 'Intersectional-Gender-Science-WMBM': ['intersectional_white-male',
  'intersectional_black-male',
  'gender_science',
  'gender_liberal-arts'],
 'Intersectional-Gender-Science-WMBF': ['intersectional_white-male',
  'intersectional_black-female',
  'gender_science',
  'gender_liberal-arts'],
 'Intersectional-Gender-Science-WMWF': ['intersectional_white-male',
  'intersectional_white-female',
  'gender_science',
  'gender_liberal-arts'],
 'Intersectional-Gender-Science-BMBF': ['intersectional_black-male',
  'intersectional_black-female',
  'gender_science',
  'gender_liberal-arts'],
 'Intersectional-Gender-Science-BMWF': ['intersectional_black-male',
  'intersectional_white-female',
  'gender_science',
  'gender_liberal-arts'],
 'Intersectional-Gender-Career-MF': ['intersectional_male',
  'intersectional_female',
  'gender_career',
  'gender_family'],
 'Intersectional-Gender-Career-WMBM': ['intersectional_white-male',
  'intersectional_black-male',
  'gender_career',
  'gender_family'],
 'Intersectional-Gender-Career-WMBF': ['intersectional_white-male',
  'intersectional_black-female',
  'gender_career',
  'gender_family'],
 'Intersectional-Gender-Career-WMWF': ['intersectional_white-male',
  'intersectional_white-female',
  'gender_career',
  'gender_family'],
 'Intersectional-Gender-Career-BMBF': ['intersectional_black-male',
  'intersectional_black-female',
  'gender_career',
  'gender_family'],
 'Intersectional-Gender-Career-BMWF': ['intersectional_black-male',
  'intersectional_white-female',
  'gender_career',
  'gender_family'],
 'Intersectional-Valence-BW': ['intersectional_black',
  'intersectional_white',
  'valence_pleasant',
  'valence_unpleasant'],
 'Intersectional-Valence-WMBM': ['intersectional_white-male',
  'intersectional_black-male',
  'valence_pleasant',
  'valence_unpleasant'],
 'Intersectional-Valence-WMBF': ['intersectional_white-male',
  'intersectional_black-female',
  'valence_pleasant',
  'valence_unpleasant'],
 'Intersectional-Valence-WMWF': ['intersectional_white-male',
  'intersectional_white-female',
  'valence_pleasant',
  'valence_unpleasant'],
 'Intersectional-Valence-WFBM': ['intersectional_white-female',
  'intersectional_black-male',
  'valence_pleasant',
  'valence_unpleasant'],
 'Intersectional-Valence-BFBM': ['intersectional_black-female',
  'intersectional_black-male',
  'valence_pleasant',
  'valence_unpleasant'],
 'Intersectional-Valence-WFBF': ['intersectional_white-female',
  'intersectional_black-female',
  'valence_pleasant',
  'valence_unpleasant'],
 'Intersectional-Valence-FM': ['intersectional_female',
  'intersectional_male',
  'valence_pleasant',
  'valence_unpleasant']}